import PyGenerator.AST
import PyGenerator.Emitter
import PyGenerator.Writer
import PyGenerator.Tests

open Lean
open PyGenerator

def main : IO Unit := do
  IO.println "=== Lean 4 Python Transpiler (lean-py-generator) ==="
  let failedCount ← PyGenerator.runTests

  if failedCount > 0 then
    IO.Process.exit 1

  IO.println "\nWriting sample Python script via writeSource (with ruff formatting)..."
  let sampleAST := SExpr.list [
    SExpr.sym "progn",
    SExpr.list [SExpr.sym "comment", SExpr.str "Generated by lean-py-generator"],
    SExpr.list [SExpr.sym "import", SExpr.sym "math"],
    SExpr.list [
      SExpr.sym "def", SExpr.sym "hypotenuse", SExpr.list [SExpr.sym "a", SExpr.sym "b"],
      SExpr.list [
        SExpr.sym "declare",
        SExpr.list [SExpr.sym "type", SExpr.sym "float", SExpr.sym "a"],
        SExpr.list [SExpr.sym "type", SExpr.sym "float", SExpr.sym "b"],
        SExpr.list [SExpr.sym "values", SExpr.sym "float"]
      ],
      SExpr.list [
        SExpr.sym "return",
        SExpr.list [
          SExpr.sym "math.sqrt",
          SExpr.list [
            SExpr.sym "+",
            SExpr.list [SExpr.sym "**", SExpr.sym "a", SExpr.int 2],
            SExpr.list [SExpr.sym "**", SExpr.sym "b", SExpr.int 2]
          ]
        ]
      ]
    ],
    SExpr.list [SExpr.sym "print", SExpr.list [SExpr.sym "fstring", SExpr.str "hypot(3, 4) = {hypotenuse(3.0, 4.0)}"]]
  ]

  writeSource "output_sample" sampleAST

  IO.println "Writing sample Jupyter Notebook via writeNotebook (with jq formatting)..."
  let nbCode := [
    SExpr.list [SExpr.sym "markdown", SExpr.str "# lean-py-generator Jupyter Notebook Demo", SExpr.str "Generated automatically by Lean 4."],
    SExpr.list [SExpr.sym "python", sampleAST]
  ]

  writeNotebook "output_sample.ipynb" nbCode

  IO.println "Successfully generated output_sample.py and output_sample.ipynb!"
